
# Resource configuration for computer
resource:
  # The path to the directory containing the core js library files.
  coreLibraryPath: Library/
  
  # The path to the module in core library that should be used as the entry point for any computer.
  entryPointModule: ./Entrypoint.js
  
  # The path to the directory containing the assets for the computer.
  assetsPath: Assets/
  
  # The path to the font definition file in the assets directory. Should be mono-spaced BMFont XML.
  fontDefinitionPath: Monogram/Monogram.xml
  
  # The path to the font texture file in the assets directory.
  fontTexturePath: Monogram/Monogram.png

# UI configuration for computer screen
ui:
  # The width of the computer screen in pixels. (!) Should be calculated as (canvasWidth - 8) * scale factor.
  windowWidth: 888
  
  # The height of the computer screen in pixels. (!) Should be calculated as (canvasHeight + 24) * scale factor.
  windowHeight: 556

# Render API configuration
render:
  # The width of the canvas in pixels that the computer will render to.
  canvasWidth: 452
  
  # The height of the canvas in pixels that the computer will render to.
  canvasHeight: 256
  
  # This will be multiplied by the font size in the BMFont file to determine the default font size in Render API.
  fontDefaultScale: 1

# Engine configuration
engine:
  # If true, the js engine will be reset when a fatal error occurs in a script. Otherwise the computer will be disabled.
  shouldResetScriptOnFatalError: true

# Storage configuration
storage:
  # Enable or disable persistent storage for the computer. The persistent storage is save with the computer state into game save file.
  enablePersistentStorage: true
  
  # Enable or disable external storage for the computer. The external storage is accessible in the mod folder.
  enableExternalStorage: true
  
  # The path to the directory containing the persistent storage files.
  externalStorageFolder: "storage/"

# Network configuration
network:
  # Mode of 
  # - "AllowAll" to allow all requests, (default and INSECURE)
  # - "BlockAll" to block all requests
  # - "AllowSome" to allow only requests to specific domains defined in the "allowedAddresses" list
  # - "BlockSome" to block requests to specific domains defined in the "blockedAddresses" list
  mode: AllowAll
  
  # List of domains to block when network mode is "BlockSome"
  blockedAddresses:
    - "example.com"
  
  # List of domains to allow when network mode is "AllowSome"
  allowedAddresses:
    - "example.com"
